language: ruby

rvm:
  - 2.2.1

cache: bundler

addons:
  postgresql: "9.3"

services:
  - elasticsearch

before_script:
  - sleep 10
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
