language: ruby

rvm:
  - 2.2.1

addons:
  postgresql: "9.3"

services:
  - elasticsearch

before_script:
  - sleep 10
  - curl -XDELETE 'http://127.0.0.1:9200/*'
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
