development:
  zenodo_server: https://sandbox.zenodo.org/

test:
  zenodo_server: https://sandbox.zenodo.org/

production:
  # FIXME TEMP Deploy and test with sandbox first!
  zenodo_server: https://sandbox.zenodo.org/
#  zenodo_server: https://zenodo.org/
